name: Deploy DRF to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VPS_HOST: ${{ secrets.SERVER_IP }}
        VPS_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key $VPS_USER@$VPS_HOST << 'EOF'
          cd ~/github_actions
          git pull origin main
          source ../venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          # اگه سشن قبلی وجود داره، متوقفش کن
          screen -S django -X quit || true
          # سرور رو توی سشن جدید اجرا کن
          screen -dmS django bash -c "source ../venv/bin/activate && python manage.py runserver 0.0.0.0:8000"
        EOF
