name: Deploy to VPS

on:
  push:
    branches:
      - main  # اجرا هنگام Push روی شاخه main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # دریافت کد پروژه
    - name: Cache Docker layers
      uses: actions/cache@v3

    # راه‌اندازی Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # کش کردن لایه‌های Docker برای افزایش سرعت Build
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # ورود به Docker Hub بدون Secrets
    - name: Log in to Docker Hub
      run: |
        echo "dckr_pat_Q4kfrG9v_85uwA7I9YqOSLB4PfQ" | docker login -u "mhmdrezachizari" --password-stdin

    # ساخت و انتشار Docker Image
    - name: Build and push Docker image
      run: |
        docker build -t mhmdrezachizari/myapp:latest .
        docker push mhmdrezachizari/myapp:latest

    # ورود به VPS و استقرار پروژه
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: "YOUR_VPS_IP"
        username: "YOUR_VPS_USERNAME"
        key: "YOUR_SSH_PRIVATE_KEY"
        port: 22
        script: |
          docker pull mhmdrezachizari/myapp:latest
          docker stop myapp || true
          docker rm myapp || true
          docker run -d --name myapp -p 80:8000 mhmdrezachizari/myapp:latest
