name: CI/CD Pipeline for Docker and VPS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "dckr_pat_Q4kfrG9v_85uwA7I9YqOSLB4PfQ" | docker login -u "mhmdrezachizari" --password-stdin

      # Step 2: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t mhmdrezachizari/myapp:latest -f Dockerfile .
          docker push mhmdrezachizari/myapp:latest

      # Step 3: Deploy to VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: "62.60.198.45"
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Make sure to store your SSH key in GitHub Secrets
          port: 22
          script: |
            cd /path/to/project/directory
            docker pull mhmdrezachizari/myapp:latest
            docker-compose down
            docker-compose up -d
