name: CI/CD Pipeline for VPS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Log in to the server using SSH and deploy the project
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: "62.60.198.45"  # IP of your VPS
          username: "root"  # Username for your VPS (could be different)
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Your SSH private key stored in GitHub Secrets
          port: 22  # Port for SSH connection (default is 22)
          script: |
            # Change to your project directory on the server
            cd /path/to/your/project

            # Pull the latest code from GitHub repository (make sure git is installed)
            git pull origin main

            # Install dependencies (example: if you're using Node.js or Python)
            # For a Node.js app, run:
            # npm install
            # For a Python app, run:
            # pip install -r requirements.txt

            # Restart your application (example: for a Node.js app using pm2)
            # pm2 restart your-app-name
            # For a Django app, you might use:
            # python manage.py migrate
            # python manage.py collectstatic --noinput
            # systemctl restart your-app-service  # If you're using a systemd service for your app
