name: Deploy to VPS

on:
  push:
    branches:
      - main  # این به این معناست که این Workflow برای هر بار Push به شاخه main اجرا می‌شود.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout کد پروژه
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # ورود به Docker Hub با استفاده از Secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    # ساخت و پخش Docker Image
    - name: Build and push Docker image
      run: |
        docker build -t myapp .
        docker push myapp

    # ورود به VPS با استفاده از SSH Key و انجام استقرار
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        port: 22
        script: |
          cd
